title: Isabella Sims # your name (or website title) here
logo: "/images/Screen Shot 2021-01-08 at 12.53.29 PM.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Isabella. I'm a senior at American University persuing a computer science bachelors degree with a concentration in software engineering. I'm also a tutor, TA, and research assistant.
  <br><br>
  As an aspiring software engineer, I am currently seeking out full-time, entry-level developer roles for Fall of 2021. 
  <br><br>
  <!--
  I enjoy using code creatively to solve problems and tell stories with data. I am also passionate about product development, love to work in teams, and am eager to learn new things.
  <br><br>
  -->

  <a href="https://www.linkedin.com/in/isabellasims/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://software-and-stuff.medium.com/">Check Out My Medium Page</a> 
  <!--
  <a href="https://github.com/isabellasims">Browse My Github</a> 
  -->
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
